services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fox_app
    ports:
      - "6001:6001"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@local_postgres:5432/foxpassportrepublic
    env_file:
      - .env
    restart: unless-stopped
